# Generated by Django 2.2.16 on 2020-10-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='goalsTeamOne',
            new_name='goals_team_one',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='goalsTeamTwo',
            new_name='goals_team_two',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='dayToEnd',
            new_name='last_day',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='teamOne',
            new_name='team_one',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='teamTwo',
            new_name='team_two',
        ),
    ]
