# Generated by Django 2.2.16 on 2020-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0003_auto_20201013_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='money_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.CharField(default='Quartas de Final', max_length=24),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='Partida Ainda Não Finalizada', max_length=28),
        ),
    ]
