# Generated by Django 2.2.16 on 2020-10-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0004_auto_20201013_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bettors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
