# Generated by Django 2.2.16 on 2020-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0006_auto_20201014_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_one', models.IntegerField(default=0)),
                ('goals_team_two', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolaoApp.Bet'),
        ),
    ]
