# Generated by Django 2.2.16 on 2020-10-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0007_auto_20201014_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.CharField(default=None, max_length=28),
        ),
    ]
