# Generated by Django 2.2.16 on 2020-10-15 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0008_bet_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bets',
        ),
        migrations.AddField(
            model_name='bet',
            name='bettor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bet',
            name='goals_team_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='goals_team_two',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals_team_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals_team_two',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
