# Generated by Django 2.2.16 on 2020-10-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0009_auto_20201014_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='game',
            new_name='game_name',
        ),
    ]
