# Generated by Django 2.2.16 on 2020-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0010_auto_20201015_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
    ]
