# Generated by Django 2.2.16 on 2020-10-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0011_game_game_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bettors',
        ),
    ]
