# Generated by Django 2.2.16 on 2020-10-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0012_remove_game_bettors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credits',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
