# Generated by Django 2.2.16 on 2020-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoApp', '0013_auto_20201020_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='Aposta Ainda Não Finalizada', max_length=28),
        ),
    ]
